name: manga_vibe
description: "Sumérgete en el mundo de los mangas con MangaVibe , la app perfecta para disfrutar de tus historias favoritas, con una interfaz intuitiva, actualizaciones diarias y un catálogo lleno de emociones que te mantendrán pegado a la pantalla."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  pdf: ^3.10.7
  image: ^4.1.3
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false